### PR TITLE
Implementation of graph browsing

### PR DESCRIPTION
**Pull request by Aurif**
Code-wise implementation of the browser part of the graph browsing, along with a set of current data files.

### CODE REVIEW

**Review by Ostrzyciel — CHANGES_REQUESTED** [review]
- Was this tested?
- Why are the jsonld files included here? Shouldn't they be pushed automatically by the CI in the OpenCS repo? I'd like to ask you to submit a PR that doesn't include the data files, so that I can properly review it – this doesn't even load properly on GitHub's website.

**Comment by Bartosz7** [comment]
The precomputed browser data has been removed. The website repo may be populated with ci/cd precomputed data by triggering a new tagged release (workflow works only for `main` branch)

**Comment by Aurif** [comment]
> * Was this tested?

Yes, we tested this on a fork of repository through github pages.

**Comment by Ostrzyciel** [comment]
Something broke in the CI... not sure due to which team's change, but please go and have a look at it, OK? https://github.com/OpenCS-ontology/OpenCS/issues/39

**Review by Ostrzyciel — APPROVED** [review]

**Pull request merged**
